#!/bin/bash

set +e
need_reboot=

res=$(cat /etc/group | grep 'toxphone')
if [ -z "$res" ]; then
    addgroup toxphone
fi

res=$(groups $SUDO_USER | grep 'toxphone')
if [ -z "$res" ]; then
    adduser $SUDO_USER toxphone
    need_reboot=yes
fi

if [ "$need_reboot" = "yes" ]; then
    echo "The user $SUDO_USER added to the toxphone group. Need reboot computer"
fi

chown -R root:toxphone /etc/toxphone
chown -R root:toxphone /var/opt/toxphone
chmod -R ug=rwX,o=rX   /var/opt/toxphone

response=
cat << EOF
Select launch mode for ToxPhone client:
1 - launch application in user space;
2 - launch application as system service.
If used GUI it is recommended to select the launch mode in user space (1)
EOF
read -r -p "Enter 1 (default) or 2: " response; response=${response:-'1'}

# 2 - As system service
if [ "$response" -eq 2 ]; then
    echo "Selected launch: as service"

    sed -e "s/%TARGET_USER%/$SUDO_USER/" \
        -i /etc/systemd/system/toxphone.service

    systemctl daemon-reload

    systemctl unmask toxphone.service
    systemctl enable toxphone.service
    systemctl start  toxphone.service

    if [ -e /etc/init/toxphone.conf ]; then
        initctl reload-configuration
    fi

# 1 - As application in user space
else
    echo "Selected launch: in user space"

    systemctl daemon-reload

    if [ -e /etc/systemd/system/toxphone.service ]; then
        systemctl stop    toxphone.service
        systemctl disable toxphone.service
        rm -f /etc/systemd/system/toxphone.service
    fi

    if [ ! -d /home/$SUDO_USER/.config/autostart ]; then
        mkdir -p /home/$SUDO_USER/.config/autostart
        chown ${SUDO_USER}:${SUDO_USER} /home/$SUDO_USER/.config/autostart
    fi

    ln -sf /opt/toxphone/autorun/toxphone-autorun.desktop  /home/$SUDO_USER/.config/autostart/toxphone-autorun.desktop
    su -c "XDG_RUNTIME_DIR=/run/user/$SUDO_UID /opt/toxphone/autorun/toxphone-autorun" $SUDO_USER
fi

if [ -e /etc/systemd/system/toxphone-cpufreq.service ]; then
    systemctl unmask toxphone-cpufreq.service
    systemctl enable toxphone-cpufreq.service
    systemctl start  toxphone-cpufreq.service
fi

systemctl daemon-reload
udevadm control --reload-rules

exit 0
