#!/bin/bash

if [ ! -e /etc/systemd/system/toxphone.service ]; then
    killall toxphone-watchdog 2> /dev/null
    sleep 1
    killall toxphone 2> /dev/null
    sleep 3
fi

res=$(systemctl list-unit-files | grep 'toxphone.service')
if [ -n "$res" ]; then
    systemctl stop    toxphone.service
    systemctl disable toxphone.service
fi

res=$(systemctl list-unit-files | grep 'toxphone-cpufreq.service')
if [ -n "$res" ]; then
    systemctl stop    toxphone-cpufreq.service
    systemctl disable toxphone-cpufreq.service
fi

exit 0
