#!/bin/bash

if [ ! -e /etc/systemd/system/toxphone.service ]; then
    killall toxphone-watchdog 2> /dev/null
    sleep 1
    killall toxphone 2> /dev/null
    sleep 3
else
    res=$(systemctl list-unit-files | grep toxphone)
    if [ -n "$res" ]; then
        systemctl stop toxphone
    fi
fi

exit 0
