#!/bin/bash

if [ ! -e /etc/systemd/system/toxphone.service ]; then
    killall toxphone-watchdog 2> /dev/null
    sleep 1
    killall toxphone 2> /dev/null
fi

res=$(systemctl list-unit-files | grep 'toxphone.service')
if [ -n "$res" ]; then
    systemctl stop    toxphone.service
    systemctl disable toxphone.service
    #systemctl mask   toxphone.service
fi

res=$(systemctl list-unit-files | grep 'toxphone-cpufreq.service')
if [ -n "$res" ]; then
    systemctl stop    toxphone-cpufreq.service
    systemctl disable toxphone-cpufreq.service
fi

#rm -f /etc/xdg/autostart/toxphone-autorun.desktop

exit 0
