#!/bin/bash

res=$(systemctl list-unit-files | grep toxphone)
if [ -n "$res" ]; then
    systemctl stop toxphone
    systemctl disable toxphone
    #systemctl mask toxphone
fi

if [ -e /etc/init/toxphone.conf ]; then
    rm -f /etc/init/toxphone.conf
    initctl reload-configuration
fi

exit 0
