#!/bin/bash

set -u

project_name=toxphone
product_dir=toxphone

SUDO=
rebuild=
print_help=
build_mode=release
need_packages=

build_packages=

install_toxphone=
install_toxphoneconf=

remove_toxphone=
remove_toxphoneconf=

# Директория этого скрипта
script_dir=$(dirname $(readlink -f $0))
echo "script_dir: $script_dir"

# Определение параметров host-системы
if [ ! -e $script_dir/setup/scripts/os_detect ]; then
    echo "Error: os_detect script not found"
    exit 1
fi
. $script_dir/setup/scripts/os_detect

# Функция удаления отладочной информации
if [ ! -e $script_dir/setup/scripts/strip_debug_info ]; then
    echo "Error: strip_debug_info script not found"
    exit 1
fi
. $script_dir/setup/scripts/strip_debug_info
# ---

jobs=$(nproc)
[ "$jobs" -gt 24 ] && jobs=$(($jobs - 6))

# Для сборки на ARM системах с ограниченным объемом памяти
mem_size=$(free -m | sed '2!d' | sed 's/  */ /g' | cut -d' ' -f2)
[ "$mem_size" -lt 2000 ] && jobs=3
echo "jobs: $jobs"

if [ "$os_id" = "neon" ]; then
    os_id="ubuntu"
fi

function display_help()
{
cat << EOF
Usage: ${0##*/}
  -h   display this help and exit
  -r   full rebuild of project
  -d   build in 'debug' mode
  -D   build deb package
  -i   install (toxphone and toxphone-config)
  -it  install deb package toxphone
  -ic  install deb package toxphone-config
  -R   remove installation (toxphone and toxphone-config) and exit
  -Rt  remove installation toxphone and exit
  -Rc  remove installation toxphone-config and exit
EOF
}

# Обработка позиционных параметров:
#    http://wiki.bash-hackers.org/scripting/posparams
while test -n ${1:-""}
do
    case "$1" in
        -h)
            print_help=yes
            shift
            ;;
        -r)
            rebuild=yes
            shift
            ;;
        -d)
            build_mode=debug
            shift
            ;;
        -D)
            build_packages=yes
            shift
            ;;
        -i)
            install_toxphone=yes
            install_toxphoneconf=yes
            shift
            ;;
        -it)
            install_toxphone=yes
            shift
            ;;
        -ic)
            install_toxphoneconf=yes
            shift
            ;;
        -R)
            remove_toxphone=yes
            remove_toxphoneconf=yes
            shift
            ;;
        -Rt)
            remove_toxphone=yes
            shift
            ;;
        -Rc)
            remove_toxphoneconf=yes
            shift
            ;;
        -*)
            echo "Error: Unknown option: $1" >&2
            exit 1
            ;;
        *)  # No more options
            #break
            echo "Error: Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

if [ "$print_help" = "yes" ]; then
    display_help
    exit 0
fi

if [ "$remove_toxphone" = "yes" ]; then
    echo -e "\nRemove ToxPhone..."

    set +e
    res=$(dpkg -l | grep -P '^ii\s+toxphone ')
    set -e
    if [ -z "$res" ]; then
        echo "Nothing to remove, ToxPhone not installed"
    else
        sudo dpkg -r toxphone
        echo "ToxPhone was removed"
    fi
    [ "$remove_toxphoneconf" != "yes" ] && exit 0
fi

if [ "$remove_toxphoneconf" = "yes" ]; then
    echo -e "\nRemove ToxPhone config..."

    set +e
    res=$(dpkg -l | grep -P '^ii\s+toxphone-config ')
    set -e
    if [ -z "$res" ]; then
        echo "Nothing to remove, ToxPhone config not installed"
    else
        sudo dpkg -r toxphone-config
        echo "ToxPhone config was removed"
    fi
    exit 0
fi

function check_need_package()
{
    dpkg -s $1 &> /dev/null
    [ "$?" -ne 0 ] && need_packages="$need_packages $1"
}

need_packages=
check_need_package 'qt5-default'
check_need_package 'libopus-dev'
check_need_package 'libpulse-dev'
check_need_package 'libvpx-dev'
check_need_package 'libusb-dev'
check_need_package 'libconfig-dev'

if [ "$build_packages" = "yes" \
     -o "$install_toxphone" = "yes" \
     -o "$install_toxphoneconf" = "yes" ]
then
    # Необходимые пакеты
    check_need_package 'fakeroot'
    check_need_package 'debconf'
    check_need_package 'debhelper'
    check_need_package 'lintian'
    check_need_package 'hashdeep'
fi

if [ -n "$need_packages" ]; then
    echo "Error: Need to install packages:$need_packages"
    echo "    Use: sudo apt-get install $need_packages"
    exit 1
fi

if [ ! -x /usr/bin/md5deep ]; then
    if [ ! -L /usr/local/bin/md5deep ]; then
        echo "Need create symlink for md5deep"
        sudo ln -sf /usr/bin/hashdeep /usr/local/bin/md5deep
    fi
fi

git_branch=$(git status -b -s | head -n1 | sed 's/\./ /' | cut -d' ' -f2 | sed 's/\//_/g')
build_config=${build_mode}-${git_branch}
build_subdir=${build_config}
build_dir=$script_dir/build/$build_subdir

[ "$rebuild" = "yes"  ] && rm -rf $build_dir

QBS=$(which qbs)

# res=$($QBS config --list profiles.toxphone)
# if [ -z "$res" ]; then
#     echo "Error: Qbs profile toxthone not found"
#     exit 1
# fi

#
# Сборка проекта
#
set -e
$QBS build \
    --file toxphone_project.qbs \
    --build-directory ./build \
    --command-echo-mode command-line \
    --jobs $jobs \
    --no-install \
    qbs.buildVariant:$build_mode \
    project.printPackegeBuildInfo:true \
    config:$build_subdir
    #profile:toxphone

echo "Build is complete (configuration: ${build_config})"

if [ "$build_packages" != "yes" ]; then
    [ "$install_toxphone" != "yes" \
    -a "$install_toxphoneconf" != "yes" ] && exit 0
fi

#
# Создание deb-пакетов
#
package_vers=$(head -n1 VERSION)
package_date=$(date +%Y%m%d)
gitrev=$(git log -1 --pretty=%h)
package_release=${package_date}git${gitrev}
full_package_vers=${package_vers}-${package_release}

echo "---"
echo "project_name ........ $project_name"
echo "product_dir ......... $product_dir"
echo "package_vers ........ $package_vers"
echo "package_date ........ $package_date"
echo "gitrev .............. $gitrev"
echo "package_release ..... $package_release"
echo "full_package_vers ... $full_package_vers"

mkdir -p $script_dir/packages/last
rm -rf   $script_dir/packages/last/*

#
# Формирование deb-пакета для toxphone
#
if [ "$build_packages" = "yes" \
     -o "$install_toxphone" = "yes" ]
then
    . $script_dir/setup/deb-toxphone
fi

#
# Формирование deb-пакета для toxphone-config
#
if [ "$build_packages" = "yes" \
     -o "$install_toxphoneconf" = "yes" ]
then
    . $script_dir/setup/deb-toxphone-config
fi
