#!/bin/bash

#
# Формирование deb-пакета toxphone-config
#
product_name=${project_name}-config
echo "---"
echo "product_name ........ $product_name"

package_dir=$script_dir/build/${build_subdir}/deb/$product_name
echo "package_dir ......... $package_dir"

package_name="${product_name}-${full_package_vers}-${os_id}${os_ver}-${os_arch}.deb"
echo "package_name ........ $package_name"

rm -rf $package_dir

mkdir -p $package_dir/DEBIAN
mkdir -p $package_dir/opt/$product_dir
mkdir -p $package_dir/usr/share/applications

cp $script_dir/setup/deb/$product_name/DEBIAN/*  $package_dir/DEBIAN
cp ${build_dir}/bin/toxphone-config              $package_dir/opt/$product_dir
cp $script_dir/setup/toxphone-config.desktop     $package_dir/usr/share/applications

function copy_pict()
{
    mkdir -p $package_dir/usr/share/icons/hicolor/${1}/apps
    cp $script_dir/setup/icons/${1}/toxphone*.png $package_dir/usr/share/icons/hicolor/${1}/apps
    chmod -R u=rwX,go=rX $package_dir/usr/share/icons/hicolor/${1}/apps
    chmod -R u=rw,go=r   $package_dir/usr/share/icons/hicolor/${1}/apps/*
}
copy_pict "16x16"
copy_pict "24x24"
copy_pict "32x32"
copy_pict "64x64"
copy_pict "128x128"
copy_pict "256x256"

chmod -R go-w        $package_dir
chmod    u=rwx,go=rx $package_dir/DEBIAN/post*
chmod    u=rwx,go=rx $package_dir/DEBIAN/pre*
chmod -R u=rwX,go=rX $package_dir/opt/$product_dir
chmod    u=rwx,go=rx $package_dir/opt/$product_dir/toxphone-config

if [ "$build_mode" = "release" ]; then
    echo -e "\nRemoving debug info ... "
    strip --strip-debug --strip-unneeded $package_dir/opt/$product_dir/toxphone-config
fi

# Размер пакета
installed_size=$(du -s $package_dir | sed -r 's/([0-9]+).*/\1/')
echo "installed_size: $installed_size"

packet_depends=$(cat << EOS
    libc6, libqt5core5a, libqt5network5, libqt5gui5, libqt5widgets5
EOS
)

os_arch_control=$os_arch
[ "${os_arch:0:3}" = "arm" ] && os_arch_control=armhf

sed -e "s/%VERSION%/${package_vers}-${package_date}git${gitrev}/" \
    -e "s/%ARCHITECTURE%/${os_arch_control}/" \
    -e "s/%INSTALLED_SIZE%/${installed_size}/" \
    -e "s/%DEPENDS%/${packet_depends}/" \
    -i $package_dir/DEBIAN/control

# Контрольные суммы файлов пакета
cd $package_dir
md5deep -rl -o f opt >> DEBIAN/md5sums
md5deep -rl -o f usr >> DEBIAN/md5sums
chmod  0644 DEBIAN/md5sums
cd $script_dir

# Создание deb-пакета
fakeroot dpkg-deb --build $package_dir ${build_dir}/$package_name

# Проверка deb-пакета
echo "Start 'lintian'"
set +e
lintian --suppress-tags \
hardening-no-relro,\
binary-or-shlib-defines-rpath,\
dir-or-file-in-opt,\
bad-package-name,\
package-not-lowercase,\
systemd-service-file-outside-lib,\
maintainer-script-calls-systemctl,\
file-in-etc-not-marked-as-conffile,\
maintainer-script-ignores-errors,\
maintainer-script-empty, \
killall-is-dangerous \
${build_dir}/$package_name
set -e

if [ "$build_packages" = "yes" ]; then
    cd $script_dir
    mkdir -p packages
    echo "Copying the file $package_name to directory ./packages"
    cp -f ${build_dir}/$package_name ./packages
    cp -f ${build_dir}/$package_name ./packages/last
fi

if [ "$install_toxphoneconf" = "yes" ]; then
    echo "Install ${product_name} config..."
    sudo dpkg -i ${build_dir}/$package_name
    echo "${product_name} config installation is complete"
fi
