#!/bin/bash

#
# Performs the watchdog-function when ToxPhone is started in user mode
#

# Disable multiple launch of script
min_pid=$(ps axw -o pid,command | grep -P '^\s*\d+\s+/bin/bash.+toxphone-watchdog$' | cut -f1 -d' ' | sort | head -n1)
[ -n "$min_pid" -a  "$min_pid" != "$$" ] && exit 0;

toxphone=/opt/toxphone/toxphone
while true; do
    res=$(ps axw -o command | grep -P "^/opt/toxphone/(toxphone\$|toxphone )" | grep -v 'grep')
    if [ -z "$res" -a -x $toxphone ]; then
        set -e
        sleep 10
        set +e
        $toxphone &
    fi
    sleep 60
done
